### ISSUE TITLE
environment setup getpass error

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/canvas-get-group-csv#6]
`Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement getpass
ERROR: No matching distribution found for getpass
failed
CondaEnvException: Pip failed`

**Comment by markoprodanovic** [comment]
@alisonmyers did removing get pass from the environment.yml solve the issue?

**Comment by alisonmyers** [comment]
yes!
